### ISSUE TITLE
fsatanize=fuzzer-no-link

### ISSUE THREAD

**Issue by aragon5956** [php/web-php#1024]
hello i have problem to configure php8.3 by download link : `https://www.php.net/distributions/php-8.3.8.tar.gz` on php.net

i've this error : 

`alexandre@alexandre-developpeur:~/Téléchargements/php-8.3.8$ sudo apt-get install build-essential
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
build-essential est déjà la version la plus récente (12.10ubuntu1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
alexandre@alexandre-developpeur:~/Téléchargements/php-8.3.8$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-linux-gnu/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 13.2.0-4ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-13-XYspKM/gcc-13-13.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-13-XYspKM/gcc-13-13.2.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.0 (Ubuntu 13.2.0-4ubuntu3) 
alexandre@alexandre-developpeur:~/Téléchargements/php-8.3.8$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-linux-gnu/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 13.2.0-4ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-13-XYspKM/gcc-13-13.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-13-XYspKM/gcc-13-13.2.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.0 (Ubuntu 13.2.0-4ubuntu3) 
alexandre@alexandre-developpeur:~/Téléchargements/php-8.3.8$ ./configure --with-password-argon2 --enable-sysvmsg --enable-sysvsem  --enable-sysvshm  --enable-zend-test --with-zip    --enable-sysvmsg  --enable-sysvsem  --enable-sysvshm   --with-sodium  --with-external-libcrypt --enable-soap  --enable-mbstring   --enable-intl  --enable-gd-jis-conv  --enable-dl-test  --enable-exif --enable-ftp   --enable-calendar  --enable-dba  --enable-bcmath --with-xsl    --enable-mysqlnd     --with-kerberos --with-imap-ssl --enable-gd   --with-external-gd --with-avif   --with-webp --with-jpeg  --with-xpm  --with-freetype --with-openssl-dir   --with-fpm-systemd  --with-fpm-acl --with-fpm-apparmor  --with-fpm-selinux  --enable-fuzzer  --enable-litespeed --disable-phpdbg  --enable-phpdbg-debug  --enable-phpdbg-readline --enable-fpm   --with-libxml   
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether cc accepts -g... yes
checking for cc option to enable C11 features... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking how to run the C preprocessor... cc -E
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking whether ln -s works... yes
checking for system library directory... lib
checking whether to enable runpaths... yes
checking if compiler supports -Wl,-rpath,... yes
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for bison... bison
checking for bison version... 3.8.2 (ok)
checking for re2c... re2c
checking for re2c version... 3.1 (ok)
checking for php... php
checking for php version... 8.2.10 (ok)
checking whether to enable computed goto gcc extension with re2c... no
checking whether C compiler accepts -ffp-contract=off... yes
checking whether C compiler accepts -fvisibility=hidden... yes
checking whether to force non-PIC code in shared modules... no
checking whether we are using musl libc... no
checking whether to use -D_GNU_SOURCE cflag... yes
checking for global register variables support... yes
checking whether __cpuid_count is available... yes
checking for pthreads_cflags... -pthread
checking for pthreads_lib... pthread

Configuring SAPI modules
checking for Apache 2 handler module support via DSO through APXS... no
checking for setproctitle... no
checking for sys/pstat.h... no
checking for PS_STRINGS... no
checking for CLI build... yes
checking for embedded SAPI library support... no
checking for FPM build... yes
checking for clearenv... yes
checking for setproctitle... (cached) no
checking for setproctitle_fast... no
checking for library containing socket... none required
checking for library containing inet_addr... none required
checking for setpflags... no
checking for clock_gettime... yes
checking for ptrace... yes
checking whether ptrace works... yes
checking for proc mem file... mem
checking if gcc supports __sync_bool_compare_and_swap... yes
checking for TCP_INFO... yes
checking for TCP_CONNECTION_INFO... no
checking for sysconf... yes
checking for times... yes
checking for kqueue... no
checking for port framework... no
checking for /dev/poll... no
checking for epoll... yes
checking for select... yes
checking for libsystemd >= 209... yes
checking for systemd/sd-daemon.h... yes
checking for acl user/group permissions support... checking for sys/acl.h... no
no
checking for sys/apparmor.h... yes
checking for aa_change_profile in -lapparmor... yes
checking for selinux/selinux.h... yes
checking for security_setenforce in -lselinux... yes
checking for clang fuzzer SAPI... yes
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking how to run the C++ preprocessor... g++ -E
checking whether C compiler accepts -fsanitize=fuzzer-no-link... no
configure: error: Compiler doesn't support -fsanitize=fuzzer-no-link
`

could you help me ?
Cordially

**Comment by tiffany-taylor** [comment]
Hello! Please submit this question to the php-general mailing list. There is information on how to subscribe to mailing lists on the [PHP Mailing Lists page](https://www.php.net/mailing-lists.php).

This repo is for the functionality of the PHP website.

**Comment by aragon5956** [comment]
ok, so i 've the solution

do `wget https://apt.llvm.org/llvm.sh
`,then `chmod u+x llvm.sh `, then `sudo ./llvm.sh 19
`, then add to your ~/.bashrc file ` export CC=clang-19` , ` export CXX=clang++-19`

ant to remove  the previous versions, do : 
`sudo apt remove clang-* llvm-* libc++-* libc++abi-* libclang-* libclc-* libfuzzer-* libomp-* lld-* lldb-*`
and 
`sudo apt purge clang-* llvm-* libc++-* libc++abi-* libclang-* libclc-* libfuzzer-* libomp-* lld-* lldb-*` and then for clean : 
`sudo apt clean`, and then 
`sudo apt autoremove`
to remove the unsued packages : 
`sudo apt autoremove`


and then, for install missing  necessary packages  : 
`sudo apt -f install
sudo dpkg --configure -a `


so if you don't want add the environment variables, you executethe configure executable file like this: 
`./configure --with-password-argon2 --enable-sysvmsg --enable-sysvsem  --enable-sysvshm  --enable-zend-test --with-zip    --enable-sysvmsg  --enable-sysvsem  --enable-sysvshm   --with-sodium  --with-external-libcrypt --enable-soap  --enable-mbstring   --enable-intl  --enable-gd-jis-conv  --enable-dl-test  --enable-exif --enable-ftp   --enable-calendar  --enable-dba  --enable-bcmath --with-xsl    --enable-mysqlnd     --with-kerberos --with-imap-ssl --enable-gd   --with-external-gd --with-avif   --with-webp --with-jpeg  --with-xpm  --with-freetype --with-openssl-dir   --with-fpm-systemd  --with-fpm-acl --with-fpm-apparmor  --with-fpm-selinux  --enable-fuzzer  --enable-litespeed --disable-phpdbg  --enable-phpdbg-debug  --enable-phpdbg-readline --enable-fpm   --with-libxml  --with-iconv=/usr/lib --with-ffi  --enable-bcmath --with-curl CC=clang-19 CXX=clang++-19 `

so adapt this with your own options !
Cordially
