### ISSUE TITLE
impossible to do: make uninstall

### ISSUE THREAD

**Issue by aragon5956** [php/web-php#1028]
hello ,
i can't do a `make uninstall` to remove my php 8.3 installation on this link `https://www.php.net/downloads.php` ,i 've this error:
`alexandre@alexandre-developpeur:~/Téléchargements/php-8.3.8$ make uninstall
make: *** Aucune règle pour fabriquer la cible « uninstall ». Arrêt.
alexandre@alexandre-developpeur:~/Téléchargements/php-8.3.8$ ls
 appveyor              Makefile.fragments
 benchmark             Makefile.objects
 build                 makelog.txt
 buildconf             modules
 buildconf.bat         NEWS
 CODING_STANDARDS.md   pear
 config.log            php.ini-development
 config.nice           php.ini-production
 config.status         README.md
 config.txt            README.REDIST.BINS
 configuration.txt     run-tests.php
 configure             sapi
 configure.ac          scripts
 CONTRIBUTING.md       SECURITY.md
 docs                  ssl.txt
 ecli                  tests
 error.txt             travis
 ext                   TSRM
 EXTENSIONS           'udo apt install --reinstall ubuntu-desktop gdm3'
 include               UPGRADING
 libs                  UPGRADING.INTERNALS
 libtool               venv
 LICENSE               win32
 main                  Zend
 Makefile
alexandre@alexandre-developpeur:~/Téléchargements/php-8.3.8$ 
`
could you help me ?
Regards

**Comment by tiffany-taylor** [comment]
Hello! Please submit this question to the [php-general mailing list](https://www.php.net/mailing-lists.php), as this question is not related to the website code on php.net.

**Comment by aragon5956** [comment]
hello ,
nobody answer to my question by php-mail-list :`<html><body>

  | php-install@lists.php.net
-- | --



</body>
</html>`

Cordially

**Comment by tiffany-taylor** [comment]
Viewable here: https://news-web.php.net/php.install/20571

Given that you had sent the email earlier today, I recommend waiting a little longer.
