### ISSUE TITLE
Add hacktoberfest label

### ISSUE THREAD

**Issue by lhsazevedo** [php/web-php#1106]
I know it's a bit late, but would like to suggest adding the hacktoberfest label to the repository. This will attract new contributors and ensure that PRs automatically count towards Hacktoberfest without needing the `hacktoberfest-accepted` label on each merged PR. The label can safely removed in late November.

**Comment by sy-records** [comment]
Thanks for the suggestion.

Modifying the tags of a repository requires additional permissions.
There won't be a lot of PR, so I'd still recommend adding the tags manually.
