### ISSUE TITLE
Search panel makes infinite loop requests in main page 

### ISSUE THREAD

**Issue by texnicii** [php/web-php#1122]
On the main page request to "https://www.php.net/js/search-index.php?lang=ru" is too many repeating and looks like infinite loop.

![telegram-cloud-photo-size-2-5300784139655572273-y](https://github.com/user-attachments/assets/c87d9990-5376-486f-b500-bba222ea0ef2)

I have cleared browser cache and refresh the main page, it repeated.

UPD:  The same in incognito mode (even just not typed something into search form)

**Comment by cmb69** [comment]
Indeed! Does not happen for "de" (haven't checked others).

**Comment by sy-records** [comment]
I think it's incorrectly being cached without content, so it's causing duplicate requests.

<img width="1096" alt="image" src="https://github.com/user-attachments/assets/e5469f3d-70d1-4629-93c8-4544f58aae5a">

**Comment by sy-records** [comment]
It's back to normal now.
