### ISSUE TITLE
8.4 announcement page seems to confuse the PDO RFCs

### ISSUE THREAD

**Issue by zerocrates** [php/web-php#1156]
The title and RFC link in the big feature callouts for PDO is [PDO Driver specific SQL parsers](https://wiki.php.net/rfc/pdo_driver_specific_parsers) but the example and description are about [PDO driver specific subclasses](https://wiki.php.net/rfc/pdo_driver_specific_subclasses).

**Comment by takaram** [comment]
Fixed by #1154
