### ISSUE TITLE
Bad Gateway error 502

### ISSUE THREAD

**Issue by RushilJalal** [php/web-php#1163]
![image](https://github.com/user-attachments/assets/46afa60b-5cdd-4ecc-9a3f-8e8266f5f636)

**Comment by cmb69** [comment]
Confirmed.

**Comment by saundefined** [comment]
Hi!
Thanks for the issue, investigating the error is already underway

**Comment by anupdebnath** [comment]
Having the same issue, I am from BD.

**Comment by heiglandreas** [comment]
See https://fosstodon.org/@php/113538828818218806

**Comment by shrekuu** [comment]
https://php.mirrors.linwise.com/
Thanks PHP team. For the record, I have to read the docs. I deployed it on my VPS. Anyone have to read the docs, come and grab a seat :)

**Comment by saundefined** [comment]
php.net has recovered, thanks to all!

**Comment by nargotik** [comment]
For transparency It would @saundefined be good to know if the downtime was been caused by any security issue.

Where can we find information about the cause ?

**Comment by saundefined** [comment]
@nargotik It was some kind of network issue, team will do a post-mortem report a bit later
