### ISSUE TITLE
Minor mistake in the PHP 8.4 example code for property hooks

### ISSUE THREAD

**Issue by nitori** [php/web-php#1169]
Hi,

I just noticed a very minor mistake in the example code at
https://www.php.net/releases/8.4/en.php

In the first example, the property hooks, on the right side it shows:

```php
        get => \sprintf("%s_%s", $this->languageCode, $this->countryCode);
        set (string $value) {
            [$this->countryCode, $this->languageCode] = explode('_', $value, 2);
        }
```

The `get` assumes `languageCode` comes first, but the `set` expects `countryCode` as first item.

It should be the other way around for the setter, as the country code is at the end.

Greetings
Sani

**Comment by saundefined** [comment]
@nitori thanks!
