### ISSUE TITLE
Recursion in the Russian version of the documentation.

### ISSUE THREAD

**Issue by ShurinokOleksandr** [php/web-php#1192]
![Screenshot_3](https://github.com/user-attachments/assets/cf60f7b2-e3de-4f98-a078-df5b0063f0d2)

**Comment by sy-records** [comment]
Thank you for your feedback.

Duplicate of #1122

**Comment by ShurinokOleksandr** [comment]
Thanks for the answer , but did you manage to solve anything? :)

**Comment by ShurinokOleksandr** [comment]
> [sy-records](/sy-records)



> Thank you for your feedback.
> 
> Duplicate of #1122
Thanks for the answer , but did you manage to solve anything? :)
