### ISSUE TITLE
Proposal to add PageGen time to each page

### ISSUE THREAD

**Issue by Willtech** [php/web-php#440]
For various reasons including search indexing and server performance include PageGen time in the footer of each generated page.

**Comment by Willtech** [comment]
UPdate footer creation as follows:

```html
<footer>
<div class="container footer-content">
<div class="row-fluid">
<ul class="footmenu">
<li><a href="/copyright.php">Copyright &copy; 2001-2021 The PHP Group</a></li>
<li><a href="/my.php">My PHP.net</a></li>
<li><a href="/contact.php">Contact</a></li>
<li><a href="/sites.php">Other PHP.net sites</a></li>
<li><a href="/privacy.php">Privacy policy</a></li>
<li><a href="https://github.com/php/web-php/blob/master/manual%2Fen%2Ffunction.random-inc.php">View Source</a></li>
<li>(PageGen 0.736984 Seconds)</li>
</ul>
</div>
</div>
</footer>
```

**Comment by Willtech** [comment]
In every file (unless it can be batched with included)
At the beginning of the page generation
```php
//PageGen
$tt = microtime(true);
```

And, at the conclusion of the page generation, as practical as possible,
```php
<li>(PageGen <?php $tt = number_format(rtrim(sprintf("%.20f", (microtime(true) - $tt)), "0"),6,'.',',');
echo $tt; ?> Seconds)</li>
```

**Comment by Willtech** [comment]
Ideally, this would have six decimal places if less than one second, and two decimals if more than one second.

**Comment by Willtech** [comment]
Or, usiung the new method place this code as near as practical to the conclusion of page generation.

```php
<li>(PageGen <?php $tt = number_format(rtrim(sprintf("%.20f", (microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'])), "0"),6,'.',',');
                     if (strpos(($tt."0"), "0") != 0) {
                         $tt = number_format($tt,2,'.',',');
                     }
                     echo $tt; ?> Seconds)</li>
```

**Comment by cmb69** [comment]
Why? Are there any other popular sites which still do this?

**Comment by salathe** [comment]
No, thanks.

**Comment by Willtech** [comment]
> Why? Are there any other popular sites which still do this?

Sure, but if there are more front page results. This site had #1 position sometimes and front page always.
Archive:[www.willtech.com.au/shop/](https://web.archive.org/web/20091025041234/http://www.willtech.com.au/shop/accessories/cat_2.html?_a=viewCat&catId=2&SiteUser=5r04c6hdnheu1ti3ia2f5mh7g4&sort_by=name&sort_order=high)

**Comment by kelunik** [comment]
I also don't see a good reason to expose page timings.
