### ISSUE TITLE
Intro adjustments proposal

### ISSUE THREAD

**Issue by lhsazevedo** [php/web-php#453]
Hey there!

After some local experiments, I would like to propose some tweaks to the intro element of the home page, also known as hero. There are still some adjustments to be done for mobile devices, which I will do if this proposal is well accepted by the community, followed by a PR.

The goal was to use size, color, white space and call to actions to guide new visitors who might be a little confused by visual clutter. The change also empowers the PHP branding by adding a large logo above the lead, which now has a larger font and an emphasis on the "popular general-purpose scripting language" snippet.

![php2](https://user-images.githubusercontent.com/7695608/139642018-89bc193e-fd5c-4f22-b879-39d3e866b9a6.png)

Animated comparison:
![Comparisson](https://user-images.githubusercontent.com/7695608/139641955-537dfcf2-52ce-46d6-9a2e-cec4e29f446b.gif)

**Comment by adielcristo** [comment]
Thanks for the proposal! I suggest changing the "Changes" link to "Changelog", as it is a more common term (my opinion, I don't have figures/sources for that).
