### ISSUE TITLE
Report a Bug broken

### ISSUE THREAD

**Issue by eberlems** [php/web-php#457]
on https://www.php.net/manual/de/pcre.constants.php the "Report a Bug" is broken.
https://github.com/php/doc-de/issues/new?body=From%20manual%20page:%20https:%2F%2Fphp.net%2Fpcre.constants%0A%0A--- just shows the 404 error

**Comment by salathe** [comment]
I have enabled GitHub Issues for [php/doc-de](https://github.com/php/doc-de) and several other documentation translation repositories that did not have it enabled.  The "Report a Bug" link should work now.
