### ISSUE TITLE
Separate manual by PHP major versions

### ISSUE THREAD

**Issue by WinterSilence** [php/web-php#484]
Current manual combines class/function information of all PHP versions But in many cases are impossible to reflect all changes that have occurred in class/function by generic synopsis. Such attempts only confuse users. This is not very convenient, since in most cases user is looking for information about specific version he is using.  PHP7 users is not interested  functions removed in PHP5 or classes to be added in PHP8.
Extension/class page does not contain Changelog - users are forced to search changes on function/method pages.
Changelogs are generated manually, rather than generated automatically based on changes in the code, so they are often incomplete or undeclared.
Changes in properties and constants of classes are not documented anywhere!

We can solve these problems by adding content filtering by PHP version:
- Define special attribute to content sections/blocks: `<programlisting role="php" class="php5 php7">` or `<programlisting role="php" php-ver="5 7">`
- Add select PHP version to class/function pages: 5, 7, 8 and `any` (default)
- Toggle visible sections/blocks by select version

If class/function page not have element `<refsect1 role="changelog">`, then auto generates this section:
- Generate class/function stubs on build releases (I'm think many users say "thank you" if you adding stubs for inner/native classes in to release)
- Calculate diff between stubs for latest releases of major versions: 5-7, 7-8

**Comment by fvignals** [comment]
On local I use a little php 5.6.26 to launch and manage apache versions, php versions, ....
my main network and local server are on php 7.4.
I'm upgrading some  broken applications to 8.1.
Everything on 1 page is, in my mind, better, like TV I don't like zapping. 8-)
Even I suggest that manual should be reflect the upcoming version : best motivation to upgrade and be prepare.
I never anticipate my php coding.

**Comment by derickr** [comment]
The manual and its translations are not set up to do this, and this will require a lot of work. Therefore I am closing this with "not planned".
