### ISSUE TITLE
Mailing list subscribe page not working

### ISSUE THREAD

**Issue by lgretton** [php/web-php#491]
The facility to subscribe to mailing lists at [https://www.php.net/mailing-lists.php](https://www.php.net/mailing-lists.php) is not working. Any attempt to subscribe returns the error:

_We were unable to subscribe you due to some technical problems.
Please try again later._

Furthermore, trying to report this problem isn't as easy as it ought to be, I'm not sure if this is the right place. The [Contact page](https://www.php.net/contact.php) says that the bug tracker must be used, but that is no longer accepting new reports. There is no link to this repository in the suggested alternatives.

**Comment by cmb69** [comment]
As a workaround for now, you should be able to subscribe by sending a mail to MAILINGLISTNAME-subscribe@lists.php.net (replace MAILINGLISTNAME with the actual name of the ML).

**Comment by lgretton** [comment]
Thanks, that's what I've done, and discovering that ezmlm is in use has helped.

**Comment by SIMJO7747** [comment]
#430 #702 #simjo77

**Comment by derickr** [comment]
I've updated the contact page, and I believe the mailinglist subscription should work again too.
