### ISSUE TITLE
Mention phpfoundation?

### ISSUE THREAD

**Issue by 3kbest** [php/web-php#497]
Hi, this is not an issue, but more directed as a tip.

Should you not mention that php.net has:?
https://opencollective.com/phpfoundation

**Comment by cmb69** [comment]
@pronskiy, @krakjoe, thoughts about this?

**Comment by krakjoe** [comment]
Currently, the php foundation and the php project are separate entities. 

We haven't yet had the conversation about whether we want to forge any kind of official links going forward. There is a mention about the announcement in the news archive.

I would prefer if there was more discussion, which should happen soon, before we make any official links.

I feel strongly this is premature, so I'm closing for now ... but thanks for thinking of everyone :)

We will make noise in the right places when we know what noises to make and where the right places are ...
