### ISSUE TITLE
Layout: pages without sidebars are not centered

### ISSUE THREAD

**Issue by SteveDesmond-ca** [php/web-php#500]
Steps to reproduce:
- browse to https://www.php.net/eol.php with a viewport width between 768px and 979px

Observed result:
- content is squished to the side
![Screen Shot 2022-02-24 at 13 22 45](https://user-images.githubusercontent.com/195896/155584509-65be95cf-b4ba-4dd7-ab62-847bf30f4144.png)

Expected result:
- content is spread out across the viewport, similar to at other resolutions
![Screen Shot 2022-02-24 at 13 23 01](https://user-images.githubusercontent.com/195896/155584543-d55d9407-05d8-43ba-b379-df9def61f997.png)

**Comment by kelunik** [comment]
I'm not sure whether we should prefer a consistent content width or use the remaining space. Having it empty looks weird, though.
