### ISSUE TITLE
Search bar breaks layout and hides text on viewports 768-858px

### ISSUE THREAD

**Issue by SteveDesmond-ca** [php/web-php#502]
Steps to reproduce:
- browse to https://www.php.net/downloads with a viewport width between 768 and 858px

Observed result:
- search bar is bumped down to a second row in the header bar
- top row of text in the sidebar is hidden
![Screen Shot 2022-02-24 at 13 39 33](https://user-images.githubusercontent.com/195896/155586815-fb74447e-9380-4a31-a13d-155051d2f626.png)
(note that this is scrolled up all the way on the page)

Expected result:
- search bar scales horizontally to fit on a single header row

**Comment by heffernan111** [comment]
Recommend adding, padding-top: 2.5rem; when @media (min-width: 768px) to #layout-content and .tips

Mock up below.

<img width="808" alt="Screenshot 2022-12-04 at 22 28 38" src="https://user-images.githubusercontent.com/8768990/205519186-e7981876-4444-488a-8333-baf8a0dd619f.png">

**Comment by saundefined** [comment]
Fixed in #1084
