### ISSUE TITLE
Need to get proper readable folder name using imap function

### ISSUE THREAD

**Issue by hiralmmavani** [php/web-php#503]
Hello there,
I use below code to get folder list in gmail and kakao.com. This is working fine in gmail but not working in kakao.com.

Code : 
$mbox=imap_open("{imap.gmail.com:993/imap/ssl}", "user", "pass");
    $list = imap_getmailboxes($mbox, "{imap.gmail.com:993/imap/ssl}", "*");
    $mailbox=null;
    $mailbox_name='';
    $number=0;
    foreach ($list as $key ) {
       echo $key->name; echo "<br/>";
    }exit;
    
    Here in Gmail I got result like : 
     Inbox
    Sent Messages 
    Drafts
    Spam and may more
    
    Here in kakao.com got result like :
    Inbox
  Sent Messages
  Drafts
 ???8?????h
 
 Can I got all folder name as readable folder name ?
 Let me know it is possible or not.

**Comment by saundefined** [comment]
Hey,

please use the appropriate sites to get help, such as StackOverflow.

This repository is only used for php.net website issues.
