### ISSUE TITLE
php.net blocks nbftp user-agent

### ISSUE THREAD

**Issue by johnklos** [php/web-php#506]
### Description

When NetBSD's wget-like command line ftp program (called nbftp) attempts to fetch php tarballs, an error is returned:

```ftp "https://www.php.net/distributions/php-8.0.17.tar.xz"
Trying [2a02:cb40:200::1ad]:443 ...
Requesting https://www.php.net/distributions/php-8.0.17.tar.xz
ftp: Error retrieving file `503 Service Temporarily Unavailable'
```

On the same machine, wget succeeds, so it appears the web servers are blocking nbftp's user-agent (NetBSD-ftp/20210826, where 20210826 is the version).

Although this is a web server issue and not a php issue, I cannot contact the webmasters as listed on https://www.php.net/contact.php because the address there requires senders be subscribed.

### PHP Version

All

### Operating System

NetBSD

**Comment by cmb69** [comment]
Maybe @saschaschumann can have a look at this.

**Comment by 1ma** [comment]
This has now become a problem for Docker, too. Until last week I was able to download the source tarballs with the `ADD url .` keyword, now I can't. I don't know what User-Agent Docker uses but as @johnklos mentions curl and wget still work.

Reproducing Dockerfile:
```
FROM alpine:latest

ADD https://www.php.net/distributions/php-8.1.6.tar.gz .
```

Output:
```
$ docker build -t phptest .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine:latest
 ---> e66264b98777
Step 2/2 : ADD https://www.php.net/distributions/php-8.1.6.tar.gz .
ADD failed: failed to GET https://www.php.net/distributions/php-8.1.6.tar.gz with status 503 Service Unavailable: <!DOCTYPE html><html><head><title>Security Check...
```

The returned HTML looks like this:
![error](https://user-images.githubusercontent.com/1456708/171839326-e5213228-91f6-4490-959f-3249ed813e98.png)

**Comment by 1ma** [comment]
Alright, this looks fixed from my end.

**Comment by johnklos** [comment]
This works via nbftp as well. Thanks!

**Comment by 1ma** [comment]
> This has now become a problem for Docker, too. Until last week I was able to download the source tarballs with the `ADD url .` keyword, now I can't. I don't know what User-Agent Docker uses but as @johnklos mentions curl and wget still work.
> 
> Reproducing Dockerfile:
> 
> ```dockerfile
> FROM alpine:latest
> 
> ADD https://www.php.net/distributions/php-8.1.6.tar.gz .
> ```
> 
> Output:
> 
> ```
> $ docker build -t phptest .
> Sending build context to Docker daemon  2.048kB
> Step 1/2 : FROM alpine:latest
>  ---> e66264b98777
> Step 2/2 : ADD https://www.php.net/distributions/php-8.1.6.tar.gz .
> ADD failed: failed to GET https://www.php.net/distributions/php-8.1.6.tar.gz with status 503 Service Unavailable: <!DOCTYPE html><html><head><title>Security Check...
> ```
> 
> The returned HTML looks like this: ![error](https://user-images.githubusercontent.com/1456708/171839326-e5213228-91f6-4490-959f-3249ed813e98.png)


@cmb69 this started happening again a few days ago. Exactly as I described in 2022-06-03.
