### ISSUE TITLE
A small typo (not sure)

### ISSUE THREAD

**Issue by usta** [php/web-php#507]
In release info page 

https://github.com/php/web-php/blob/50be982f55591db1a726e8255e33292067f6f9b7/releases/8.1/release.inc#L240
to
https://github.com/php/web-php/blob/50be982f55591db1a726e8255e33292067f6f9b7/releases/8.1/release.inc#L259

I think min 5 -> 6 is a typo

**Comment by cmb69** [comment]
Good catch, thank you!
