### ISSUE TITLE
The design could be better

### ISSUE THREAD

**Issue by khnbzkrt** [php/web-php#513]
Are you considering making the design of the php.net website more modern?

**Comment by cmb69** [comment]
IMO we can leave it as is; it will be modern at some point in the future again. ;)

**Comment by khnbzkrt** [comment]
> IMO we can leave it as is; it will be modern at some point in the future again. ;)

What is IMO? I don't understand :(

**Comment by cmb69** [comment]
"IMO" is an acronym of "in my opinion". But my comment was rather meant in an ironical way.

To be honest, yes, we should modernize the look of the Website. However, there is insufficient time, so unless somebody provides a (set of) pull request(s), it won't happen. But before you (or anybody else for that matter) start working on that, consider to write to the php.net internal infrastructure discussion [mailing list](https://www.php.net/mailing-lists.php) and suggest your proposal there.
