### ISSUE TITLE
How to set my default language to English

### ISSUE THREAD

**Issue by samuelgfeller** [php/web-php#555]
I live in Switzerland (German-speaking part), and php.net docs are all in German per default. 

The programming language is English however, and I do all my work related browsing in English. All docs, forums, blogs etc. and having php.net in German feels very weird, and I don't like it at all. 

Is there a way to permanently set the default language to English so that I don't have to switch the language each time? 
My Windows language is English and browser (Edge) as well.

**Comment by cmb69** [comment]
You can set your preferences via https://www.php.net/my.php. There are some glitches, though, some of them tracked in the [old bug tracker](https://bugs.php.net).

**Comment by samuelgfeller** [comment]
Default there was already `en`. And it's true that the site is in English and when browsing on it the docs as well. 
But as I'm browser with Google, it's them that mess it up. When I click on a link that points to php.net the doc is in German.

![image](https://user-images.githubusercontent.com/31797204/175261364-2bd9ea1f-ff70-45de-bda2-a6ae5a36955f.png)

I would love that the site takes the setting in "php.net/my.php" even when Google thinks best for me is German..

**Comment by cmb69** [comment]
Yeah, that is one of those issues, see https://bugs.php.net/bug.php?id=73918.
