### ISSUE TITLE
Should it be possible to download PHP files?

### ISSUE THREAD

**Issue by localheinz** [php/web-php#579]
Running

```shell
curl -v https://www.php.net/include/branches.inc
```

allows me to download [`include/branches.inc`](https://github.com/php/web-php/blob/b2ff80507c59fe702ef1f10ad9c255ac9242b07d/include/branches.inc).

**Comment by derickr** [comment]
That check email func file to removed from the repo in 2001:

```
commit 0925042c8942a8de7ef6cf2f822df32c4899ca0e
Author: Jesus M. Castagnetto <jmcastagnetto@php.net>
Date:   Wed Feb 28 12:48:33 2001 +0000

    removed check_email_func.php
```

I'll remove it from the server by hand (I don't think rsync takes care of it).
