### ISSUE TITLE
Submitting new notes

### ISSUE THREAD

**Issue by kamil-tekiela** [php/web-php#590]
Why does the code send a POST request to `https://main.php.net` when submitting a note? How can I locally submit a note? This repo doesn't contain that file from what I can see, and yet the notes are read using a simple function in this repo. How does this work? 

https://github.com/php/web-php/blob/16f4045cf0f7a35a4edd766ec6eaf79d554e53cd/manual/add-note.php#L97

**Comment by cmb69** [comment]
The repo for main.php.net is php/web-master, and it contains https://github.com/php/web-master/blob/main/public/entry/user-note.php. user-note.php stores the submitted user note in the database, and this repo reads the user notes from there (or maybe there is an intermediate step).

To fake this for testing purposes, you would need a working setup of web-master locally, and then to fiddle with your etc/host file. The latter could be simplified by allowing to configure the URL.

**Comment by kamil-tekiela** [comment]
I figured out that there are already some notes committed in Git so I can use that for testing. I can also download more notes straight from php.net as the files aren't protected and are in the web root.
