### ISSUE TITLE
Releases RSS/ATOM feed does not validate

### ISSUE THREAD

**Issue by AndrewGearhart** [php/web-php#676]
The [PHP Releases RSS/ATOM feed does not pass validation in the W3C Feed Validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.php.net%2Freleases%2Ffeed.php). As a result of the failures, the feed cannot be added to several feed readers (including the Slack RSS feed reader).

**Comment by cmb69** [comment]
Thanks for reporting! Could you please double-check that #678 solves this issue?

**Comment by AndrewGearhart** [comment]
It _looks_ like it will. Can't say for sure without testing... but it looks like it will resolve it!

**Comment by cmb69** [comment]
The fix should be rolled-out to the Website in a few hours. :)

**Comment by AndrewGearhart** [comment]
To follow-up, this did fix it. Thanks again for being so speedy with this!
