### ISSUE TITLE
Suggestion: Change each PHP release's color to the color of the release year

### ISSUE THREAD

**Issue by Pythone** [php/web-php#680]
### Proposal
I have an idea to have each new release be attached to the pantone color for that year so that we have something interesting for each year.

### Ways to Attach
You can have it listed in phpinfo(), have it used in the logo, have it used as an Easter egg, Have it used as a special color, have it used in the elephpant, etc.

### Color of This Year
2022's color of the year is 'Very Peri' (`PANTONE 17-3938`)
It would be implemented as `#6667AB` or `rgb(102, 103, 171)` and would improve everything.
It even has it's own website at https://veryperi.me/

**Comment by heffernan111** [comment]
2023's colour. 

https://www.color-name.com/viva-magenta.color

I love this idea

**Comment by derickr** [comment]
We have no plans to do this, so I'm closing this issue.
