### ISSUE TITLE
Improve the thanks.php page

### ISSUE THREAD

**Issue by rlerdorf** [php/web-php#682]
Could someone take a look at the thanks.php page and make it look a bit more modern?

Perhaps include logos for the current providers and a slightly longer blurb on each one if we have more we can say.

It would help a bit, especially with Digital Ocean, that have been asking for more visibility. For Digital Ocean, we can add that we have edit.php.net, bugs.php.net, museum.php.net, wiki.php.net, downloads.php.net, qa.php.net, pecl.php.net on Digital Ocean droplets.

**Comment by cmb69** [comment]
I'm afraid that only few (if any) people know which of these providers are still active, i.e. which services we still use. It might be best if the providers would file PRs about what they like to change [there](https://github.com/php/web-php/blob/master/thanks.php).

**Comment by rlerdorf** [comment]
The providers usually have no idea what we are running on the servers they provide, so it is not going to come from them.

**Comment by mvriel** [comment]
I just did a very mock -or quick design- as to how the -current- sponsors section could look like; perhaps divided into 2 columns as the number of sponsors is significant enough and the screen real estate allows for it.

Would something like this be interesting?

![image](https://user-images.githubusercontent.com/193704/183056847-7fc29f70-b253-48b0-95fc-9ca7ce69de4a.png)

As for the legacy sponsors, it may be interesting to only show their logo and perhaps a caption with their support method as this is secondary information and to focus on current sponsors?

**Comment by rlerdorf** [comment]
Great, I like it. We don't need to do much for the legacy sponsors at this point. We can leave those are one-liners without a logo for now, although I suppose that might make the page look unbalanced.

**Comment by mvriel** [comment]
Unless someone else beats me to it, I can find some time during the weekend to make a PR for this

**Comment by mvriel** [comment]
During implementation, I discovered that when using 2 columns, some of the texts would become 3 lines high and make the mock above look messy. This is a screenshot of the current implementation
![image](https://user-images.githubusercontent.com/193704/183212047-2fd84e01-004b-491b-ba65-1efff1502771.png)

There are one or two alignment issues to iron out, and I'll be issuing a PR of this without changing the 'Thanks Emiritus' section. I can attack that issue in a subsequent PR to keep things small and incremental

**Comment by derickr** [comment]
This seems to have been merged, and hence this issue can be closed?
