### ISSUE TITLE
Missing manpage reports 200 OK

### ISSUE THREAD

**Issue by vasartam** [php/web-php#694]
From manual page: https://php.net/function.http-build-url

---

This page can be accessed through search engine results, although it is empty.

Is this an expected behaviour?

**Comment by vasartam** [comment]
For some reason, the link that was automatically pasted in the issue header wasn't the same I was click a "Report a Bug" button on (is this a bug?).

I was meant to send this link: https://php.uz/manual/en/function.http-build-url.php

This is top 1 result for "php http_build_url" search query on Google for me.

**Comment by jimwins** [comment]
Looks like https://php.net/function.http-build-url does show a search result on the docs, as expected.

https://php.uz/manual/en/function.http-build-url.php returns a 404, and it's not a website that the PHP org controls, maybe it's a vestige of the old mirror system?

This issue can probably be closed.
