### ISSUE TITLE
Regarding the license of the stylesheets referenced in phd and redistribution

### ISSUE THREAD

**Issue by athos-ribeiro** [php/web-php#711]
Hi,

The following files are referred to and fetched from phd when building with the `PHP` package (in `phpdotnet/phd/Package/PHP/ChunkedXHTML.php`):

* https://www.php.net/styles/theme-base.css (styles/theme-base.css)
* https://www.php.net/styles/theme-medium.css (styles/theme-medium.css)

While the phd project is shipped under MIT/BSD licenses, web-php and its files have no other license notices other than the notice on copyright.php which says that the design and layout of php.net is protected by trade dress and should not be copied nor imitated. Does this apply to both files above? In special, styles/theme-base.css seems to be derived from bootstrap, and the apache license disclaimer was kept. Is it still ditributed through the apache license then?

My concern is regarding the possibility of preparing and shipping offline documentation for users in Debian/Ubuntu.

Thanks!

**Comment by cmb69** [comment]
Yeah, that is ugly, but I'm not sure what we can do about that. Changing the license would require the PHP Group to agree, but it's unlikely that we can contact all or at least most of them nowadays. :(

**Comment by athos-ribeiro** [comment]
Thanks, Christoph!

I do understand the issue at this point. Thanks for clarifying anyway. I will check if I can write a simple stylesheet just to make local docs builds readable then (feel free to close this issue now).

**Comment by heiglandreas** [comment]
> [...]Changing the license would require the PHP Group to agree, but it's unlikely that we can contact all or at least most of them nowadays. :(

If that is a challenge, the question is: Shouldn't we take on that challenge to replace the PHP Group from License and other topics with a different body that will not be difficult to contact in 10 years time? Not that I think we need to replace the PHP Group, but if that will be an issue, then we should think about how to mitigate that risk. And rather sooner than later IMO...

**Comment by cmb69** [comment]
> Shouldn't we take on that challenge to replace the PHP Group from License and other topics with a different body that will not be difficult to contact in 10 years time?

I would welcome that, but I think that requires the PHP Group to agree to that. So we're back at square one.

Maybe @rlerdorf has some ideas?
