### ISSUE TITLE
Contact page says to email webmaster, but only subscribed users can send to that address

### ISSUE THREAD

**Issue by jegelstaff** [php/web-php#759]
Hello,

This is the page: https://www.php.net/contact.php

It says "If you would like to contact the webmasters for some other reason, please write to [php-webmaster@lists.php.net](mailto:php-webmaster@lists.php.net)"

When you email that address, you get a bounce back to say that only subscribers can send to that address, since it is tied to the mailing list(s).

So.... subscription details/instructions should be added to the page? Or the email address should be changed?

--Julian

**Comment by jjdunn** [comment]
@Girgias - I see you recently committed to the web-php repo.  Can you address this issue?  Like the ticket reporter, I also want to send feedback/suggestions about how to improve www.php.net, and this seems to be impossible.

**Comment by Girgias** [comment]
I don't maintain web-php, the commits were about fixing the wording of the glibc vulnerability news entry.

@derickr might have a better idea about the list issue, but if you want to provide feedback or suggestions, just submitting an issue or PR seems like a better idea to me. But then again I don't work on the website.

**Comment by saundefined** [comment]
I'd suggest:

or hide this paragraph altogether, offering a GitHub for feedback and suggestions, as it says at the top of the page,

or in the «Note that this address is mapped to a mailing list and a newsgroup, so every message you send will be stored in public archives at multiple servers» make the «mailing list» a link to https://www.php.net/mailing-lists.php in this case it will be clear what needs to be done.

What do you think?
