### ISSUE TITLE
What license is the php documentation codebase?

### ISSUE THREAD

**Issue by frob** [php/web-php#773]
I noticed the drupal.org supported versions page could use a new supported versions graph. I was going to write my own generator but saw yours was on github. It isn't quite clear what the license is on the php code that runs the php docs pages. Would you mind other open source projects using this code?

**Comment by derickr** [comment]
The website's code and style's licence is described in https://www.php.net/copyright.php, which is linked from the "[Copyright © 2001-2023 The PHP Group](https://www.php.net/copyright.php)" link at the bottom of each page.

The PHP *docs* code and tools are different.

- `phd`, the tool that creates HTML (and other formats) from Docbook is licensed under the [MIT](https://github.com/php/phd/blob/master/LICENSE) license.
- The layout and style, being the same as the PHP website, is under the same license linked from [Copyright © 2001-2023 The PHP Group](https://www.php.net/copyright.php)
- The documentation's sources are under a CC-BY [license](https://github.com/php/doc-base/blob/master/LICENSE).
- Many of the scripts in the `scripts/` directory of the documentation are under the [PHP license](https://github.com/php/doc-base/blob/master/scripts/revcheck.php)

To get to your specific question, the [supported-versions.php](https://github.com/php/web-php/blob/master/supported-versions.php) script and [data](https://github.com/php/web-php/blob/master/include/branches.inc) is under the same [license](https://github.com/php/web-php/blob/master/copyright.php) as the website.

Our general position here has been in the past to not have a problem with developers reusing the code, as long as the whole page layout does not reflect, or looks endorsed by, the PHP project or the PHP website layout and style.
