### ISSUE TITLE
Accused of being a bot and forced to enter a captcha

### ISSUE THREAD

**Issue by MikeRich88** [php/web-php#776]
I have never seen a screen like this before on php.net.

<img width="1179" alt="Screenshot 2023-05-14 at 4 13 37 AM" src="https://github.com/php/web-php/assets/7113073/66b54758-2c6d-4376-8b8a-86d3946a90b0">

I don't appreciate being forced to enter a captcha. There are severe accessibility issues that come along with captchas.

I am not in Germany, I am in the US. The screen occurs on 2 different ISPs when I open php.net in a private window.

**Comment by debohman** [comment]
I agree, this just started happening for me. I don't understand why this should be necessary for a site such as this. Were the security settings for the hosting service changed recently?

**Comment by debohman** [comment]
It is not happening for me in a private window. I am also in the US.

**Comment by Girgias** [comment]
This was an issue with our CDN provider.
