### ISSUE TITLE
Website eats leading spaces in code

### ISSUE THREAD

**Issue by MioVisman** [php/web-php#779]
In all translations so (4 leading spaces):
https://github.com/php/doc-en/blob/master/language/control-structures/alternative-syntax.xml#L70

And on the site like this:
https://www.php.net/manual/en/control-structures.alternative-syntax.php
![err](https://github.com/php/web-php/assets/5917956/0997369f-b4e8-42da-9219-8dc32a3a1aa0)

**Comment by TimWolla** [comment]
This is fixed with #801, but I can't close this issue.
