### ISSUE TITLE
PHP.net SSL / Configuration

### ISSUE THREAD

**Issue by eojeel** [php/web-php#820]
Receiving the following HTTP status. 

(failed)net::ERR_CERT_COMMON_NAME_INVALID

Cycling through different Common names per X refresh.

**Comment by SakiTakamachi** [comment]
I was just about to report this too.

Correct certificate:
<img width="535" alt="スクリーンショット 2023-10-31 0 28 27" src="https://github.com/php/web-php/assets/34942839/b8da010a-0467-4bdb-9f99-583dbda8eac5">

Certificate that causes an error:
<img width="517" alt="スクリーンショット 2023-10-31 0 28 54" src="https://github.com/php/web-php/assets/34942839/b6d26bde-d044-409f-9281-b2cf880d560b">

(Sorry the image is in Japanese)

In my case, the situation was as shown below.

1. Search for "empty()" on Google
2. I was able to open the page normally.
3. Search for "is_string()" on Google
4. When I opened the page, the SSL was broken. The page that was able to open normally earlier broke when I refreshed it.

**Comment by SakiTakamachi** [comment]
```
// view-source:https://www.php.net/

<!DOCTYPE html>
<html>
<head>
<!-- You should add the following <meta> viewport element to support responsive device scaling -->
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0 maximum-scale=1.0" />
<title>Speedtest Custom by Ookla</title>
</head>
<!-- Any wrapping containers around the iframe need to have width and height set to `100%` for a responsive iframe experience -->
<body style="width: 100%; height: 100%;">
<!-- Replace the "src" property with your custom Test URL -->
<!--"your-company-name" is set up in your online configuration dashboard -->
<iframe width="100%" height="650px" frameborder="0" src="http://servers-australia.speedtestcustom.com"></iframe>
</body>
</html>
```

**Comment by SakiTakamachi** [comment]
When I checked the A records for www.php.net, there were 55. Could it be that some of these IPs have failed to be retained and are being used by other servers?

**Comment by SakiTakamachi** [comment]
ping @derickr

**Comment by SakiTakamachi** [comment]
@Ayesh 
Thank you! I can confirm that it has been repaired.

**Comment by SakiTakamachi** [comment]
@TimWolla problem fixed!
