### ISSUE TITLE
Shortname/shorturl of Iterator interface leads to Object Iteration's page

### ISSUE THREAD

**Issue by biziclop** [php/web-php#822]
I guess this is the appropriate place to report this issue, it might be at somewhere inside `get_shortname()`:  
https://github.com/php/web-php/blob/6225d35e1284b80a6c28e32d71631b4014b0a3f0/include/site.inc#L208  
or maybe at `errors.inc`:   
https://github.com/php/web-php/blob/6225d35e1284b80a6c28e32d71631b4014b0a3f0/include/errors.inc

I made a simple userscript for my browser to automatically go to the shorturl link to a given page, and it worked fine so far until today, when I wanted to look up the Iterator interface's documentation, but somehow I always landed at Object iteration. Steps:

Start by opening https://www.php.net/manual/en/class.iterator.php:
```
<title>PHP: Iterator - Manual </title>
…
<link rel="canonical" href="https://www.php.net/manual/en/class.iterator.php">
<link rel="shorturl" href="https://www.php.net/iterator">
<link rel="alternate" href="https://www.php.net/iterator" hreflang="x-default">
```

Follow the shorturl: https://www.php.net/iterator, and we see that it already shows the Object Iteration page, but it shows another shorturl, the otherwise usual `oop5.iterations` one:
```
<title>PHP: Object Iteration - Manual </title>
…
<link rel="canonical" href="https://www.php.net/manual/en/language.oop5.iterations.php">
<link rel="shorturl" href="https://www.php.net/oop5.iterations">
<link rel="alternate" href="https://www.php.net/oop5.iterations" hreflang="x-default">
```

Following it: https://www.php.net/oop5.iterations of course shows the same page.

**Comment by sy-records** [comment]
Thanks for your feedback!
