### ISSUE TITLE
About eval

### ISSUE THREAD

**Issue by lin9** [php/web-php#922]
I know that eval is very high-risk, but the need to use eval in actual production projects is not common, I found that the official does not provide a solution to disable eval, in order to 1% of PHP projects have the need to use eval, and 99% of the projects are in a high-risk environment, I think PHP official is not very strong on PHP's default security.

**Comment by pronskiy** [comment]
@lin9, this seems unrelated to the website code. Consider starting a discussion on the Internals mailing list https://www.php.net/mailing-lists.php.
