### ISSUE TITLE
User Contributed Notes section title and footer do not follow selected language

### ISSUE THREAD

**Issue by leonardolara** [php/web-php#964]
The "User Contributed Notes" title at the bottom of each page is hardcoded in English (in web-php) and will not follow the selected language of the manual. The same occurs for its footer and for the Language Selection combo itself (at the top).

It would be nice if these terms could be translated to the language chosen by the user.

**Comment by tiffany-taylor** [comment]
One of the complications with this is that the PHP manual is manually translated by volunteers. It is not translated through a third-party API. However, perhaps it can be changed to where the user contributed notes _are_ fed to an API? The translation quality will not be as good as the manual, though.

**Comment by leonardolara** [comment]
I didn't mean to translate the notes but the titles, headers and footers. They could be part of the translation.
