### ISSUE TITLE
docs.php.net - still in use ?

### ISSUE THREAD

**Issue by omars44** [php/web-php#996]
As I was going through the PHP stubs of the Solr Extension, I found links to docs.php.net, which apparently is severely outdated, that says the latest php is 8.1 beta, and still has docs en, which I imagine could be as outdated. I'm gonna update the links to https://www.php.net/manual/*

From:
https://www.php.net/sites.php
<img width="1064" alt="Screenshot 2024-05-26 at 11 09 48" src="https://github.com/php/web-php/assets/110405224/d99972da-cca2-4a92-960f-5b7566cad611">

it also says "Documentation is built here four times a day."

Questions that popped shall it be named dev, if its dev. so no reliability expected ? or have redirector to php.net/manual ? or is it useful the way it is? or sites.php needs to get updated to reflect the current status?

I'm just wondering and thought to bring that to your attention,

Cheers,
Omar

**Comment by Tina-1300** [comment]
Is there a tool in PHP to create documentation automatically with the PHP documentation menu to stay in the theme?
